spring:
    jpa:
        
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        #generate-ddl: true
    sql:
        init:
            platform: mysql
    datasource:
            url: jdbc:mysql://172.19.0.2:3306/todos #?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            username: username
            password: password
            driver-class-name: com.mysql.cj.jdbc.Driver
julio:
    title: El titulo

todo:
    defaultState: TO_DO
    states: 
        - TO_DO
        - IN_PROGRESS
        - DONE
        - CANCEL
    validChanges:
        TO_DO:
            - IN_PROGRESS
            - CANCEL
        IN_PROGRESS:
            - TO_DO
            - DONE
            - CANCEL
        DONE:
            - CANCEL
        CANCEL:

log4j:
    appender:
        stdout:
            layout:
                ConversionPattern: "[%d{yyyy-MM-dd HH:mm:ss}] [ %-5p] [%c{1}:%L] %m%n"