julio:
    title: El titulo

todo:
    defaultState: TO_DO
    states: 
        - TO_DO
        - IN_PROGRESS
        - DONE
        - CANCEL
    validChanges:
        TO_DO:
            - IN_PROGRESS
            - CANCEL
        IN_PROGRESS:
            - TO_DO
            - DONE
            - CANCEL
        DONE:
            - CANCEL
        CANCEL:
