julio:
    title: El titulo

todo:
    states:
        TO_DO:
            - IN_PROGRESS
            - CANCEL
        IN_PROGRESS:
            - TO_DO
            - DONE
            - CANCEL
        DONE:
            - CANCEL
        CANCEL:
